QUERIES = [
    {
        # Name of this query, to be used in output file names
        'QueryName': 'MD-Utah',
        # These are the party types that go in the output
        'PartyType': ['DEF',],
        # Case history must contain at least one of the following EXACT words/phrases
        'DescMustContain': [],
        # Case history must not contain any of the following EXACT words/phrases
        'DescMustNotContain': [],
        # These are the search parameters
        'params': {
            'currentPage':'1',
            'sortBy':'Filing Date',
            'sortOrder':'DESC',
            'OldShowDatePanel':'false',
            'OldCourtType':'D',
            'OldSearchType':'case',
            'OldSearchScope':'county',
            'OldCaseNum':'',
            'OldCaseType':'MD',
            'OldCitationNum':'',
            'OldCountyCode':'25',
            'OldLocationCode':'',
            'OldPartyCode':'',
            'OldPartyFirstName':'',
            'OldPartyLastName':'',
            'OldBirthDate':'',
            'OldStartFilingDate':'',
            'OldEndFilingDate':'',
            'OldJudgmentStartDate':'',
            'OldJudgmentEndDate':'',
            'OldJudgmentStartDispDate':'',
            'OldJudgmentEndDispDate':'',
            'OldKaseStartDispDate':'',
            'OldKaseEndDispDate':'',
            'courtType':'district',
            'searchType':'case',
            'searchScope':'county',
            'countyCode':'25',
            'locationCode':'2502',
            'caseNumber':'',
            'caseType':'MD',
            'citationNumber':'',
            'partyLastName':'',
            'partyFirstName':'',
            'birthDate':'',
            'caseStartFilingDate':'',
            'caseEndFilingDate':'',
            'caseStartDispDate':'',
            'caseEndDispDate':'',
            'judgmentStartDate':'',
            'judgmentEndDate':'',
            'judgmentStartDispDate':'',
            'judgmentEndDispDate':'',
            'message':'',
            }
    },


    {
        # Name of this query, to be used in output file names
        'QueryName': 'DC-Utah',
        # These are the party types that go in the output
        'PartyType': ['PLA', 'DEF',],
        # Case history must contain at least one of the following EXACT words/phrases
        'DescMustContain': [],
        # Case history must not contain any of the following EXACT words/phrases
        'DescMustNotContain': [],
        # These are the search parameters
        'params': {
            'currentPage':'1',
            'sortBy':'Judgment Date',
            'sortOrder':'DESC',
            'OldShowDatePanel':'false',
            'OldCourtType':'D',
            'OldSearchType':'judgment',
            'OldSearchScope':'county',
            'OldCaseNum':'',
            'OldCaseType':'DC',
            'OldCitationNum':'',
            'OldCountyCode':'25',
            'OldLocationCode':'',
            'OldPartyCode':'',
            'OldPartyFirstName':'',
            'OldPartyLastName':'',
            'OldBirthDate':'',
            'OldStartFilingDate':'',
            'OldEndFilingDate':'',
            'OldJudgmentStartDate':'',
            'OldJudgmentEndDate':'',
            'OldJudgmentStartDispDate':'',
            'OldJudgmentEndDispDate':'',
            'OldKaseStartDispDate':'',
            'OldKaseEndDispDate':'',
            'courtType':'district',
            'searchType':'judgment',
            'searchScope':'county',
            'countyCode':'25',
            'locationCode':'2502',
            'caseNumber':'',
            'caseType':'DC',
            'citationNumber':'',
            'partyLastName':'',
            'partyFirstName':'',
            'birthDate':'',
            'caseStartFilingDate':'',
            'caseEndFilingDate':'',
            'caseStartDispDate':'',
            'caseEndDispDate':'',
            'judgmentStartDate':'',
            'judgmentEndDate':'',
            'judgmentStartDispDate':'',
            'judgmentEndDispDate':'',
            'message':'',
            }
    },


    {
        # Name of this query, to be used in output file names
        'QueryName': 'CN-Utah',
        # These are the party types that go in the output
        'PartyType': ['PLA', 'DEF',],
        # Case history must contain at least one of the following EXACT words/phrases
        'DescMustContain': ['REVENUE DETAIL - TYPE: COMPLAINT 0K-2K'],
        # Case history must not contain any of the following EXACT words/phrases
        'DescMustNotContain': [],
        # These are the search parameters
        'params': {
            'currentPage':'1',
            'sortBy':'Judgment Date',
            'sortOrder':'DESC',
            'OldShowDatePanel':'false',
            'OldCourtType':'D',
            'OldSearchType':'judgment',
            'OldSearchScope':'county',
            'OldCaseNum':'',
            'OldCaseType':'CN',
            'OldCitationNum':'',
            'OldCountyCode':'25',
            'OldLocationCode':'',
            'OldPartyCode':'',
            'OldPartyFirstName':'',
            'OldPartyLastName':'',
            'OldBirthDate':'',
            'OldStartFilingDate':'',
            'OldEndFilingDate':'',
            'OldJudgmentStartDate':'',
            'OldJudgmentEndDate':'',
            'OldJudgmentStartDispDate':'',
            'OldJudgmentEndDispDate':'',
            'OldKaseStartDispDate':'',
            'OldKaseEndDispDate':'',
            'courtType':'district',
            'searchType':'judgment',
            'searchScope':'county',
            'countyCode':'25',
            'locationCode':'2502',
            'caseNumber':'',
            'caseType':'CN',
            'citationNumber':'',
            'partyLastName':'',
            'partyFirstName':'',
            'birthDate':'',
            'caseStartFilingDate':'',
            'caseEndFilingDate':'',
            'caseStartDispDate':'',
            'caseEndDispDate':'',
            'judgmentStartDate':'',
            'judgmentEndDate':'',
            'judgmentStartDispDate':'',
            'judgmentEndDispDate':'',
            'message':'',
            }
    },

]



